baseURL = "https://www.youprogress.info/"
title = "Полезное питание, здоровый образ жизни и методы лечения: советы и рецепты"
author = "Admin"
copyright = "YOUPROGRESS.INFO"
paginate = 10
languageCode = "ru"
defaultContentLanguage = "ru"
enableInlineShortcodes = true
theme = "tailwind"
enableRobotsTXT = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]

[markup.tableOfContents]
endLevel = 2
order = false
startLevel = 2

[header]
  logo = "snowy-owl.png"
  sticky = false

[footer]
  since = 2024
  poweredby = true

[markup]
  _merge = "deep"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  commit = false
  rss = true
  canonifyURLs = true


[params.header]
    logo = "favico.png"

[params.footer]
    since = 2024
    poweredby = false

[languages]
[languages.ru]
languageCode = 'ru-RU'
languageName = 'Russian'
weight = 1
[languages.ru.params]
a = 'a'

[search]
  summaryInclude = 180 # show only part of content in search result.
  minMatchCharLength = 2 # https://www.fusejs.io/api/options.html#minmatchcharlength
  threshold = 0.3 # https://www.fusejs.io/api/options.html#threshol
  
[menu]

[[menu.main]]
    identifier = "health"
    name = "ЗДОРОВЬЕ"
    pageRef = "/health"
    weight = 1

[[menu.main]]
    identifier = "food"
    name = "ПОЛЕЗНЫЕ ПРОДУКТЫ"
    pageRef = "/food"
    weight = 2

  [[menu.main]]
    identifier = "product"
    name = "ТОВАРЫ ДЛЯ ЗДОРОВЬЯ"
    pageRef = "/product"
    weight = 3

  [[menu.main]]
    identifier = "work"
    name = "ЗАРАБОТАЙ В ИНТЕРНЕТЕ"
    pageRef = "/work/works.md"
    weight = 4


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[services]
  [services.disqus]
    shortname = 'https-mark199317-github-io-blogws'

[social_media]
  [[social_media.items]]
    enabled = true
    title = 'Face-book'
    icon = 'brand-facebook'
    link = 'https://www.facebook.com/'

  [[social_media.items]]
    enabled = true
    title = 'Twit-ter'
    icon = 'brand-x'
    link = 'https://twitter.com/'

  [[social_media.items]]
    enabled = true
    title = 'Inst-agram'
    icon = 'brand-instagram'
    link = 'https://www.instagram.com/'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.120.0"